# Generated by Django 5.2.9 on 2025-12-26 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_login_business_type_login_company_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='company_email',
        ),
        migrations.RemoveField(
            model_name='login',
            name='company_status',
        ),
        migrations.RemoveField(
            model_name='login',
            name='contact_email',
        ),
        migrations.AddField(
            model_name='login',
            name='services_offered',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='verification_status',
            field=models.CharField(choices=[('PENDING_VERIFICATION', 'Pending Verification'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_VERIFICATION', max_length=50),
        ),
        migrations.AddField(
            model_name='login',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='login',
            name='business_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='government_id',
            field=models.FileField(blank=True, null=True, upload_to='company_documents/ids/'),
        ),
        migrations.AlterField(
            model_name='login',
            name='license_document',
            field=models.FileField(blank=True, null=True, upload_to='company_documents/licenses/'),
        ),
        migrations.AlterField(
            model_name='login',
            name='usertype',
            field=models.CharField(choices=[('traveler', 'Traveler'), ('company', 'Company')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='verification_submitted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
