# Generated by Django 5.2.9 on 2025-12-26 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_login_company_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='verified_by',
        ),
        migrations.RemoveField(
            model_name='login',
            name='view_password',
        ),
        migrations.AlterField(
            model_name='login',
            name='government_id',
            field=models.FileField(blank=True, null=True, upload_to='documents/ids/'),
        ),
        migrations.AlterField(
            model_name='login',
            name='license_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/licenses/'),
        ),
        migrations.AlterField(
            model_name='login',
            name='usertype',
            field=models.CharField(choices=[('traveler', 'Traveler'), ('company', 'Company')], default='traveler', max_length=20),
        ),
        migrations.AlterField(
            model_name='login',
            name='verification_status',
            field=models.CharField(choices=[('PENDING_VERIFICATION', 'Pending Verification'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_VERIFICATION', max_length=20),
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('VERIFICATION_SUBMITTED', 'Company Verification Submitted'), ('VERIFICATION_APPROVED', 'Company Verification Approved'), ('VERIFICATION_REJECTED', 'Company Verification Rejected'), ('NEW_COMPANY', 'New Company Registration'), ('SYSTEM', 'System Notification')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
