# Generated by Django 5.2.9 on 2025-12-26 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_login_verified_by_remove_login_view_password_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminnotification',
            options={},
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='document_type',
            field=models.CharField(blank=True, choices=[('LICENSE', 'License Document'), ('GOVERNMENT_ID', 'Government ID')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='government_id_rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='government_id_status',
            field=models.CharField(choices=[('NOT_SUBMITTED', 'Not Submitted'), ('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_SUBMITTED', max_length=20),
        ),
        migrations.AddField(
            model_name='login',
            name='license_document_status',
            field=models.CharField(choices=[('NOT_SUBMITTED', 'Not Submitted'), ('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_SUBMITTED', max_length=20),
        ),
        migrations.AddField(
            model_name='login',
            name='license_rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='type',
            field=models.CharField(choices=[('VERIFICATION_SUBMITTED', 'Verification Submitted'), ('VERIFICATION_APPROVED', 'Verification Approved'), ('VERIFICATION_REJECTED', 'Verification Rejected'), ('DOCUMENT_REJECTED', 'Document Rejected'), ('DOCUMENT_APPROVED', 'Document Approved'), ('ACTION_REQUIRED', 'Action Required'), ('NEW_COMPANY', 'New Company')], max_length=50),
        ),
        migrations.AlterField(
            model_name='login',
            name='government_id',
            field=models.FileField(blank=True, null=True, upload_to='company_documents/government_ids/'),
        ),
        migrations.AlterField(
            model_name='login',
            name='license_document',
            field=models.FileField(blank=True, null=True, upload_to='company_documents/licenses/'),
        ),
    ]
