# Generated by Django 5.2.9 on 2025-12-30 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_adminnotification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='view_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
