# Generated by Django 5.2.9 on 2025-12-30 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_login_view_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration_days', models.IntegerField(help_text='Duration in days')),
                ('vibe_tag', models.CharField(choices=[('ADVENTURE', 'Adventure & Thrill'), ('CHILL', 'Chill & Relax'), ('PARTY', 'Party Crowd'), ('SPIRITUAL', 'Spiritual & Wellness'), ('SOLO_FRIENDLY', 'Solo Friendly'), ('DIGITAL_DETOX', 'Digital Detox'), ('ROMANTIC', 'Couples/Romantic'), ('CULTURE', 'Culture & History')], max_length=50)),
                ('trip_type', models.CharField(max_length=100)),
                ('age_min', models.IntegerField(default=18)),
                ('age_max', models.IntegerField(default=60)),
                ('gender_restriction', models.CharField(choices=[('ANY', 'Mixed Group (Any)'), ('FEMALE_ONLY', 'Female Only'), ('MALE_ONLY', 'Male Only'), ('COUPLES_ONLY', 'Couples Only')], default='ANY', max_length=20)),
                ('max_capacity', models.IntegerField()),
                ('current_bookings', models.IntegerField(default=0)),
                ('itinerary_details', models.TextField(help_text='Detailed day-wise itinerary')),
                ('social_activities', models.TextField(blank=True, help_text='Ice-breakers, games, etc.', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TripImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trip_images/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('is_cover', models.BooleanField(default=False)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.trip')),
            ],
        ),
    ]
