# Generated by Django 5.2.9 on 2025-12-31 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_tripchat_tripupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='interests',
            field=models.TextField(blank=True, help_text='Comma-separated list of interests', null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
