# Generated by Django 5.2.9 on 2026-01-02 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_login_tier_trip_view_count_report_review_wallet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='type',
            field=models.CharField(choices=[('VERIFICATION_SUBMITTED', 'Verification Submitted'), ('VERIFICATION_APPROVED', 'Verification Approved'), ('VERIFICATION_REJECTED', 'Verification Rejected'), ('DOCUMENT_REJECTED', 'Document Rejected'), ('DOCUMENT_APPROVED', 'Document Approved'), ('ACTION_REQUIRED', 'Action Required'), ('NEW_COMPANY', 'New Company'), ('TRIP_STARTING', 'Trip Starting'), ('TRIP_ONGOING', 'Trip Ongoing'), ('TRIP_COMPLETED', 'Trip Completed'), ('TRIP_CANCELLED', 'Trip Cancelled')], max_length=50),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved & Active'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended'), ('PAUSED', 'Paused by Company'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='TravelerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BOOKING_CONFIRMED', 'Booking Confirmed'), ('BOOKING_CANCELLED', 'Booking Cancelled'), ('TRIP_STARTING_SOON', 'Trip Starting Soon'), ('TRIP_ONGOING', 'Trip is Ongoing'), ('TRIP_COMPLETED', 'Trip Completed'), ('TRIP_UPDATE', 'Trip Update'), ('TRIP_CANCELLED', 'Trip Cancelled'), ('REVIEW_REMINDER', 'Review Reminder')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.booking')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
