# Generated by Django 5.2.10 on 2026-02-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_adminnotification_type_alter_trip_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='num_females',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='num_males',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='num_others',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
