# Generated by Django 5.2.10 on 2026-02-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_booking_num_females_booking_num_males_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved & Active'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended'), ('PAUSED', 'Paused by Company'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
    ]
