# Generated by Django 5.2.10 on 2026-03-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_trip_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='type',
            field=models.CharField(choices=[('VERIFICATION_SUBMITTED', 'Verification Submitted'), ('VERIFICATION_APPROVED', 'Verification Approved'), ('VERIFICATION_REJECTED', 'Verification Rejected'), ('DOCUMENT_REJECTED', 'Document Rejected'), ('DOCUMENT_APPROVED', 'Document Approved'), ('ACTION_REQUIRED', 'Action Required'), ('NEW_COMPANY', 'New Company'), ('TRIP_STARTING', 'Trip Starting'), ('TRIP_ONGOING', 'Trip Ongoing'), ('TRIP_COMPLETED', 'Trip Completed'), ('TRIP_CANCELLED', 'Trip Cancelled'), ('TRIP_PAUSE_REQUEST', 'Trip Pause Request')], max_length=50),
        ),
        migrations.AlterField(
            model_name='trip',
            name='vibe_tag',
            field=models.CharField(choices=[('ADVENTURE', 'Adventure & Thrill'), ('CHILL', 'Chill & Relax'), ('PARTY', 'Party Crowd'), ('SPIRITUAL', 'Spiritual & Wellness'), ('SOLO_FRIENDLY', 'Solo Friendly'), ('DIGITAL_DETOX', 'Digital Detox'), ('ROMANTIC', 'Couples/Romantic'), ('CULTURE', 'Culture & History'), ('EXPLORING', 'Exploring & Sightseeing'), ('TEAM_BUILDING', 'Team Building'), ('CORPORATE', 'Corporate Retreat'), ('WEEKEND', 'Weekend Getaway'), ('NATURE', 'Nature & Wildlife')], max_length=50),
        ),
    ]
