# Generated by Django 5.2.10 on 2026-03-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='traveler_chat_last_read',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='company_chat_last_read',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
