# Generated by Django 5.2.10 on 2026-03-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_booking_traveler_chat_last_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='razorpay_key_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='razorpay_key_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
