# Generated by Django 5.2.10 on 2026-03-13 17:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_login_razorpay_key_id_login_razorpay_key_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='razorpay_key_id',
        ),
        migrations.RemoveField(
            model_name='login',
            name='razorpay_key_secret',
        ),
        migrations.AddField(
            model_name='login',
            name='email_verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='login',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
