# Generated by Django 5.2.10 on 2026-03-14 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_login_razorpay_key_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='email_verification_token',
        ),
        migrations.RemoveField(
            model_name='login',
            name='is_email_verified',
        ),
        migrations.AddField(
            model_name='login',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EmailVerificationOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_otps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
