# Generated by Django 5.2.10 on 2026-03-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_login_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='razorpay_key_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='razorpay_key_secret',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
