# Generated by Django 5.2.10 on 2026-03-14 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_login_razorpay_key_id_login_razorpay_key_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationotp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
