# Generated by Django 5.2.10 on 2026-03-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_emailverificationotp_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('allow_registrations', models.BooleanField(default=True)),
                ('platform_name', models.CharField(default='Travel Buddy', max_length=100)),
                ('support_email', models.EmailField(default='support@travelbuddy.com', max_length=254)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('notify_new_partner', models.BooleanField(default=True)),
                ('notify_doc_upload', models.BooleanField(default=True)),
                ('send_welcome_email', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
