# Generated by Django 5.2.10 on 2026-03-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='homepage_hero_title',
            field=models.CharField(default='Find Your Perfect Group Adventure', max_length=200),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='require_otp_verification',
            field=models.BooleanField(default=True),
        ),
    ]
