# Generated by Django 5.2.10 on 2026-04-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_systemsetting_homepage_hero_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
